require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - "vendor/**/*"
    - "papierkram_api_client.gemspec"

Layout/LineLength:
  Exclude:
    - "test/cassettes/**/*"

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - "test/**/*"

Metrics/MethodLength:
  Max: 16
  CountAsOne:
    - "array"
    - "hash"
    - "heredoc"
    - "method_call"

Metrics/ParameterLists:
  Max: 8
  Exclude:
    - "lib/api/v1/**/*"

Metrics/ClassLength:
  Max: 250
  CountAsOne:
    - "array"
    - "hash"
    - "heredoc"
    - "method_call"
