# frozen_string_literal: true

require 'faraday'
require 'faraday/multipart'
require 'httpx/adapters/faraday'
require 'forwardable'
require 'tempfile'

require_relative 'papierkram_api_client/version'
require_relative 'papierkram_api/v1/helper/pdf_from_response'
require_relative 'papierkram_api/v1/helper/date_helper'
require_relative 'papierkram_api/v1/validators/expense_voucher'
require_relative 'papierkram_api/v1/endpoints/base'
require_relative 'papierkram_api/v1/endpoints/banking/bank_connections'
require_relative 'papierkram_api/v1/endpoints/banking/transactions'
require_relative 'papierkram_api/v1/endpoints/contact/companies'
require_relative 'papierkram_api/v1/endpoints/contact/companies_persons'
require_relative 'papierkram_api/v1/endpoints/expense/vouchers'
require_relative 'papierkram_api/v1/endpoints/income/estimates'
require_relative 'papierkram_api/v1/endpoints/income/invoices'
require_relative 'papierkram_api/v1/endpoints/income/payment_terms'
require_relative 'papierkram_api/v1/endpoints/income/propositions'
require_relative 'papierkram_api/v1/endpoints/info'
require_relative 'papierkram_api/v1/endpoints/projects'
require_relative 'papierkram_api/v1/endpoints/tracker/tasks'
require_relative 'papierkram_api/v1/endpoints/tracker/time_entries'

require_relative 'papierkram_api/client'
